In [1]:
# import pandas library for data manipulation and analysis
import pandas as pd

In [2]:
# read the csv file "players_20.csv" into a pandas DataFrame
df = pd.read_csv('players_20.csv')

# set index
df.set_index('short_name', inplace=True)

# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [3]:
# show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

## **sample()**

In [4]:
# extract 10 random elements from the "nationality" column
df['nationality'].sample(10, random_state=99)

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. Chudý                Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [5]:
# extract a random 20% sample of the dataframe
df.sample(frac=0.2, random_state=99)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
R. Alvarado,Roberto Alvarado,20,1998-09-07,176,70,Mexico,Cruz Azul
Qiao Wei,Wei Qiao,31,1987-07-20,187,75,China PR,Shenzhen FC
E. Paredes,Esteban Paredes,38,1980-08-01,178,82,Chile,Colo-Colo
K. Stoyanov,Krum Stoyanov,27,1991-08-01,177,71,Bulgaria,Bulgaria
M. Chudý,Martin Chudý,30,1989-04-23,187,90,Slovakia,Górnik Zabrze
...,...,...,...,...,...,...,...
Pedro León,Pedro León Sánchez Gil,32,1986-11-24,183,73,Spain,SD Eibar
M. Sykes,Mark Sykes,21,1997-08-04,182,78,Northern Ireland,Oxford United
Y. Fofana,Yahia Fofana,18,2000-08-21,194,89,France,Le Havre AC
A. Micai,Alessandro Micai,25,1993-07-24,186,77,Italy,US Salernitana 1919
David Bruno,David Dias Resende Bruno,27,1992-02-14,175,64,Portugal,Astra Giurgiu

In [6]:
# unsample: increase the sampling rate -> frac > 1 (Note: replace parameter has to be True for frac parameter > 1)
df.sample(frac=2, replace=True, random_state=99)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Hauptmeijer,Mike Hauptmeijer,22,1997-03-18,191,70,Netherlands,PEC Zwolle
A. Mosquera,Andrés Mosquera,29,1990-02-20,182,80,Colombia,Club León
V. Thill,Vincent Thill,19,2000-02-04,172,58,Luxembourg,US Orléans Loiret Football
D. Bouanga,Denis Bouanga,24,1994-11-11,180,70,Gabon,AS Saint-Étienne
S. Al Selouli,Saad Al Selouli,21,1998-05-25,168,57,Saudi Arabia,Ettifaq FC
...,...,...,...,...,...,...,...
M. Connor,Matthew Connor,22,1997-04-08,192,82,Republic of Ireland,Waterford FC
J. Northcott,Jordan Northcott,17,2002-02-09,162,60,Scotland,St. Johnstone FC
A. Bodzek,Adam Bodzek,33,1985-09-07,184,81,Poland,Fortuna Düsseldorf
J. Adebayo-Smith,Jordan Adebayo-Smith,18,2001-01-11,181,77,United States,Lincoln City
F. Mac Allister,Francis Manuel Mac Allister,23,1995-10-30,176,71,Argentina,Argentinos Juniors